name: flutter_dashboard
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  fl_chart: ^0.70.2
  provider: ^6.1.2
  flutter_staggered_grid_view: ^0.7.0
  firebase_core: ^3.12.1
  firebase_ui_firestore: ^1.7.1
  cloud_firestore: ^5.6.5
  shared_preferences: ^2.5.2
  firebase_storage: ^12.4.4
  grouped_list: ^6.0.0
  image_picker: ^1.1.2
  rxdart: ^0.28.0
  flutter_screenutil: ^5.9.3
  line_awesome_flutter: ^3.0.1

  expandable_text: ^2.3.0
  flutter_iconly: ^1.0.2
  cached_network_image: ^3.4.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/tabbar/bold/
    - assets/icons/tabbar/light/
    - assets/icons/light/
    - assets/icons/bold/
    - assets/icons/products/
    - assets/icons/profile/
    - assets/icons/detail/
    - assets/images/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
  
